### ISSUE TITLE
DMZ Migration: Complete DMZ migration

### ISSUE THREAD

**Issue by brandtheisey** [USStateDept/communities#22]
- [ ] fix corrupted export of gravity forms data on DMZ
- [ ] import "fixed" data 
- [ ] decommission external sites

**Comment by trycrmr** [comment]
Broken out into three other associated issues. Search "DMZ Migration" for status of associated issues.

**Comment by trycrmr** [comment]
Activities to be continued after the site owners and end users of the wordpress.state.gov site are unable to access the content or the site to make updates. Their access is currently slated to be cut off COB March 4th.

**Comment by dstepp** [comment]
OBE. Divided into new issues.
