### ISSUE TITLE
Migrate/move Ecuador Wordpress files

### ISSUE THREAD

**Issue by kchurch05** [USStateDept/communities#54]
Need @ZackoGB's help with this. Last resort is to dump DB tables and do a find/replace on the file, then upload to OpenNet

**Comment by brandtheisey** [comment]
Can you explain the issue a bit more? Did we miss a site or files from a site when migrating from the DMZ?

**Comment by kchurch05** [comment]
^ [See slack convo]

**Comment by kchurch05** [comment]
Able to get site content (aka pages/posts) off extranet and imported into OpenNet. Currently moving 21+ GB of media files from extranet to OpenNet.  05 ran out of space on the E: drive so @ZackoGB has opened a ticket with ESOC for 60 more GBs

**Comment by kchurch05** [comment]
More space added; need to move rest of files off BIDS-JUMP onto C:  local and then upload back to 05
