### ISSUE TITLE
FSI Consular Training

### ISSUE THREAD

**Issue by mallorylh** [USStateDept/communities#55]
Customer needs assistance with possible issues with the use of particular theme that requires certain plugins, but not certain.

**Comment by brandtheisey** [comment]
Can we get the theme name so it can be out into the queue?

**Comment by mallorylh** [comment]
The name of the theme is Responsive by CyberChimps. They were not all that happy with the theme regardless of the plugin requirements and most likely will go with GeneratePress theme. They really liked how another community made great use of this theme.

**Comment by mallorylh** [comment]
I'm going to close this or mark it as done since customer really didn't make this a big issue and went onto something else. If they change their mind and come back expressing concern/issue with theme, we can open another issue/ticket.
